########################################################################
# Copyright (c) 1988-2014 $organization$
#
# This software is provided by the author and contributors ``as is''
# and any express or implied warranties, including, but not limited to,
# the implied warranties of merchantability and fitness for a particular
# purpose are disclaimed. In no event shall the author or contributors
# be liable for any direct, indirect, incidental, special, exemplary,
# or consequential damages (including, but not limited to, procurement
# of substitute goods or services; loss of use, data, or profits; or
# business interruption) however caused and on any theory of liability,
# whether in contract, strict liability, or tort (including negligence
# or otherwise) arising in any way out of the use of this software,
# even if advised of the possibility of such damage.
#
#   File: Makefile
#
# Author: $author$
#   Date: 11/5/2014
#
# Common Gcc Makefile for Elevation evls Executable
########################################################################

evls_CPP_SOURCES += \
${EV_SRC}/ev/fs/path/matcher.cpp \
${EV_SRC}/ev/fs/path/match/reader.cpp \
${EV_SRC}/ev/fs/path/match/read/events.cpp \
${EV_SRC}/ev/fs/path/separator.cpp \
${EV_SRC}/ev/fs/path/parts.cpp \
${EV_SRC}/ev/os/unix/fs/directory/path.cpp \
${EV_SRC}/ev/os/unix/fs/directory/entry.cpp \
${EV_SRC}/ev/app/console/ls/main.cpp \
${XOS_SRC}/xos/nadir/xos/base/main_main.cpp \

